[package]
name = "rust_primer"
version = "0.1.0"
authors = ["zct <317712914@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
